# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7de35e1dec350e667a5419c0139c138daa521090b30ed7129cfbe7bc76f9828624105ecd739f49190b0c42fa71411665403ecc8dde4c1739a6c45f254f47deff

test:
  secret_key_base: c39d51c9f3037866cf47315fd9127cfc3a87d4381e5709221d86f32a7cc5d3f8b97b649f101b799853cae58d509d0571643d4a03b562931b79450d01f9fa5192

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
